/*
	01 - REFORÇAR O ISNULL
	02 - USO DAS FUNÇÕES DE AGRUPAMENTO E CLASSIFICAÇÃO
	03 - USO DO IN EM CONSULTAS E EM EXPRESSÕES CONDICIONAIS IF, CASE...
	04 - UNION, INTERSECT, EXCEPT
	05 - SUB CONSULTAS NO SELECT
	06 - SUB CONSULTAS NO FROM/JOIN
	07 - SUB CONSULTAS NO WHERE COM USO DO IN
	08 - SUB CONSULTAS NO WHERE COM USO DO EXISTS
	09 - PIVOT E UNPIVOT
	10 - JSON
	11 - XML
*/


01 - SELECT* FROM FUNCIONARIOS F WHERE ISNULL(F.CD_BANCO, 2) = 2

01.1 - DECLARE @ID INT
		SET @ID = 1
		SELECT * FROM FUNCIONARIOS F WHERE ISNULL(@ID, 0 ) = 0 OR @ID = F.CD_FUNCIONARIO

02 - SELECT COUNT(*) AS [QTD_FUNCIONARIOS], SUM(F.SALARIO) AS [TOTAL_SALARIOS], 
		AVG(F.SALARIO) AS [MEDIA_SALARIAL], MIN(F.SALARIO) AS [MENOR_SALARIO], 
		MAX(F.SALARIO) AS [MAIOR_SALARIO], STDEV(F.SALARIO) AS [DESVIO_PADRAO], 
		VARP(F.SALARIO) AS [VARICANCIA] FROM FUNCIONARIOS F

02.1 - SELECT F.CD_DEPARTAMENTO, D.NM_DEPARTAMENTO, COUNT(*) [QTD_FUNCIONARIOS_POR_DEPARTAMENTO]
		FROM FUNCIONARIOS F JOIN DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
		GROUP BY F.CD_DEPARTAMENTO, D.NM_DEPARTAMENTO

02.2 - SELECT*, COUNT(*) OVER(PARTITION BY F.CD_DEPARTAMENTO, F.CD_BANCO)
		[QTD_FUNCIONARIOS_POR_DEPARTAMENTO_E_BANCO]	FROM FUNCIONARIOS F

02.3 - SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, D.CD_DEPARTAMENTO, D.NM_DEPARTAMENTO,
		ROW_NUMBER() OVER(ORDER BY D.NM_DEPARTAMENTO) [ROW_NUMBER_NM_DEP],
		ROW_NUMBER() OVER(ORDER BY F.NM_FUNCIONARIO) [ROW_NUMBER_NM_FUNC],
		RANK() OVER(ORDER BY D.NM_DEPARTAMENTO) [RANK],
		DENSE_RANK() OVER(ORDER BY D.NM_DEPARTAMENTO) [DENSE_RANK],
		NTILE(5) OVER(ORDER BY D.NM_DEPARTAMENTO) [NTILE]
	
		FROM FUNCIONARIOS F JOIN DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO

02.4 - SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, D.CD_DEPARTAMENTO, D.NM_DEPARTAMENTO,
		ROW_NUMBER() OVER(PARTITION BY F.CD_DEPARTAMENTO ORDER BY F.NM_FUNCIONARIO) [ROW_NUMBER_NM_FUNC]
		FROM FUNCIONARIOS F

02.5 - SELECT HASHBYTES('MD5', 'SENHA_MT_SEGURA')

03 - SELECT* FROM FUNCIONARIOS F WHERE SALARIO IN (180.0, 1500.0)

03.1 DECLARE @OPCAO VARCHAR(30) = 'RELATORIO'
	IF @OPCAO IN ('CONSULTA', 'RELATORIO')
		BEGIN
			SELECT 'CONSULTA/RELATORIO'
		END
	ELSE
		BEGIN
			SELECT 'OPCAO INVALIDA'
		END

00.TABELA_TMP - SELECT D.NM_DEPARTAMENTO, COUNT(*) AS [TOTAL_FUNCIONARIOS] 
				INTO #tabela FROM DEPARTAMENTOS D JOIN FUNCIONARIOS F ON
				D.CD_DEPARTAMENTO = F.CD_DEPARTAMENTO
				GROUP BY D.NM_DEPARTAMENTO

04 - SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO FROM FUNCIONARIOS F WHERE F.CD_DEPARTAMENTO = 4
		UNION
	SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO FROM FUNCIONARIOS F WHERE F.CD_FUNCIONARIO = 7


04.1 -  SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, CATEGORIA = 99 
			FROM FUNCIONARIOS F WHERE F.CD_DEPARTAMENTO = 4
	UNION
		SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO 
			FROM FUNCIONARIOS F WHERE F.CD_FUNCIONARIO = 7

04.2 SELECT* FROM (SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, CATEGORIA = 99 
					FROM FUNCIONARIOS F WHERE F.CD_DEPARTAMENTO = 4
						UNION
					SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO 
					FROM FUNCIONARIOS F WHERE F.CD_FUNCIONARIO = 7) T

04.EXTRA - SELECT* FROM (VALUES(1,1), (1,2)) D(X, Y)

04.3 -  SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, CATEGORIA = 4
			FROM FUNCIONARIOS F WHERE F.CD_DEPARTAMENTO = 4
	INTERSECT
		SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO 
			FROM FUNCIONARIOS F WHERE F.CD_FUNCIONARIO = 7

04.4 - SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, CATEGORIA = 4
			FROM FUNCIONARIOS F WHERE F.CD_DEPARTAMENTO = 4
	EXCEPT
		SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO 
			FROM FUNCIONARIOS F WHERE F.CD_FUNCIONARIO = 7

04.5 - 	SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO
			FROM FUNCIONARIOS F WHERE F.CD_BANCO IS NULL
				UNION
		SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO
			FROM FUNCIONARIOS F WHERE F.CD_DEPARTAMENTO IN (3, 4)
	EXCEPT
		SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO
			FROM FUNCIONARIOS F WHERE F.CD_DEPARTAMENTO IS NULL
				INTERSECT
		SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO
			FROM FUNCIONARIOS F WHERE F.CD_BANCO IN (3, 4)

05 - SELECT  D.NM_DEPARTAMENTO, (SELECT COUNT(*) FROM FUNCIONARIOS F 
		WHERE F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO) TOTAL FROM DEPARTAMENTOS D

05.1 - SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, 
		(SELECT B.NU_AGENCIA FROM BANCOS B WHERE B.CD_BANCO = F.CD_BANCO) AGENCIA,
		(SELECT B.NU_BANCO FROM BANCOS B WHERE B.CD_BANCO = F.CD_BANCO) CONTA,
		(SELECT D.NM_DEPARTAMENTO FROM DEPARTAMENTOS D WHERE D.CD_DEPARTAMENTO = F.CD_DEPARTAMENTO) DEP
		FROM FUNCIONARIOS F

		/* EQUIVALE A ISSO
			SELECT F.CD_FUNCIONARIO, F.NM_FUNCIONARIO, B.NU_AGENCIA, B.NU_BANCO, D.NM_DEPARTAMENTO 
				FROM FUNCIONARIOS F	LEFT JOIN BANCOS B ON F.CD_BANCO = B.CD_BANCO
				LEFT JOIN DEPARTAMENTOS D ON D.CD_DEPARTAMENTO = F.CD_DEPARTAMENTO
		*/

06 - SELECT T.NM_DEPARTAMENTO, MIN(T.SALARIO) MENOR_SALARIO FROM 
		(SELECT F.SALARIO, D.NM_DEPARTAMENTO FROM FUNCIONARIOS F 
			JOIN DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO ) T 
	GROUP BY NM_DEPARTAMENTO
	-- OU --
	SELECT D.NM_DEPARTAMENTO, MIN(T.SALARIO) MENOR_SALARIO FROM DEPARTAMENTOS D JOIN 
		(SELECT F.SALARIO,F.CD_DEPARTAMENTO FROM FUNCIONARIOS F) T
	ON T.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
	GROUP BY NM_DEPARTAMENTO
